"""
Django settings for example project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#######################################################################################
# Static Files Examples
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Project-level static files:
STATICFILES_DIRS = [BASE_DIR / "static"]

# In all examples, the web server should be configured to serve files from the 'public'
# directory.
# We switch between example configurations based on this environment variable.
STATIC_CONFIG = environ.get("STATIC_CONFIG", "default").lower()

# Example 1: Default static files behavior.
# This is the "default" configuration for new Django projects. No STORAGES are defined.
# Static files are collected to STATIC_ROOT, and served from there. There is no
# manifest file, so static files are served with their original names, and overwritten
# on each `collectstatic` run. This is bad for a production environment because the
# static files could change at any time, and therefore cannot be safely cached.
STATIC_URL = "static/"
MEDIA_URL = "media/"
STATIC_ROOT = BASE_DIR / "public" / "static-default"
MEDIA_ROOT = BASE_DIR / "public" / "media"

# Example 2: Using ManifestStaticFilesStorage for static files.
# This is a better configuration for production use. It uses hashed names for static
# files, which allows them to be safely cached. However, the default behavior of
# ManifestStaticFilesStorage is to write the manifest file to a fixed location:
# STATIC_ROOT/staticfiles.json. This the manifest file is overwritten on each
# `collectstatic` run. This can cause bugs during deployments or rollbacks, because the
# manifest file may not match the code that is currently being served.
if STATIC_CONFIG == "manifest":
    STATIC_ROOT = BASE_DIR / "public" / "static-manifest-default"
    STORAGES = {
        "default": {
            # Location defaults to MEDIA_ROOT
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            # Location defaults to STATIC_ROOT
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }

# Example 3: Custom static files storage with per-release manifest files.
# To avoid overwriting `staticfiles.json` every time, we define a custom storage 
# class in `storages.py` that stores the manifest file in a subdirectory named after 
# the current "release ID". If you don't pass a release id, it defaults to the git hash 
# of the current commit. (If you're not using git, you'll need to set the RELEASE_ID 
# environment variable during deployment to a unique value for each deployment, such as 
# a timestamp.) This way, old code continues using the old manifest file, and new code 
# uses the new manifest file.
# See `storages.py` for the implementation of `ExampleManifestLocalStorage`.
elif STATIC_CONFIG == "custom":
    STATIC_ROOT = BASE_DIR / "public" / "static-manifest-custom"
    RELEASE_ID = environ.get("RELEASE_ID", None)
    STORAGES = {
        "default": {
            # Location defaults to MEDIA_ROOT
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            # Location defaults to STATIC_ROOT + release_id (see storages.py)
            "BACKEND": "example.storages.ReleaseSpecificManifestLocalStorage",
            "OPTIONS": {
                "release_id": RELEASE_ID,
                "release_id_strategy": environ.get("RELEASE_ID_STRATEGY", "example.release_id_strategies.git_hash"),
            },
        },
    }

elif STATIC_CONFIG == "s3":
    # Example 4: Using S3 for static files with per-release manifest files.
    # Similar to the previous example, but using S3 for static file storage.
    
    # Ensure the required AWS settings are set in the environment.
    BUCKET_NAME = environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_ACCESS_KEY_ID = environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = environ.get("AWS_SECRET_ACCESS_KEY")
    msg = "To use S3 storage, set AWS_STORAGE_BUCKET_NAME, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY in the environment."
    assert BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, msg
    
    STATIC_ROOT = None  # Not used with S3 storage.
    # If using a CloudFront distribution or other CDN, set STATIC_URL to that.
    # NOTE: STATIC_URL MUST end in a slash (/)
    STATIC_URL = environ.get("STATIC_URL", f"https://{BUCKET_NAME}.s3.amazonaws.com/static/")
    # If using a CloudFront distribution or other CDN, set the custom domain here.
    # NOTE: CDN_DOMAIN MUST NOT end in a slash (/)
    CDN_DOMAIN = environ.get("AWS_S3_CUSTOM_DOMAIN", None)
    RELEASE_ID = environ.get("RELEASE_ID", None)
    
    # Note that we are storing Media and Static in the same bucket, but under
    # different prefixes ("media/" and "static/"). This is not required, they can be
    # in different buckets if desired.
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": BUCKET_NAME,
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "custom_domain": CDN_DOMAIN,
                "location": "media/",
            },
        },
        "staticfiles": {
            "BACKEND": "example.storages.ReleaseSpecificManifestS3Storage",
            "OPTIONS": {
                "bucket_name": BUCKET_NAME,
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "custom_domain": CDN_DOMAIN,
                "location": "static/",
                "release_id": RELEASE_ID,
                "release_id_strategy": environ.get("RELEASE_ID_STRATEGY", "example.release_id_strategies.git_hash"),
            },
        },
    }

# Purely for demonstration purposes, create the STATIC_ROOT if it doesn't exist.
if STATIC_ROOT:
    STATIC_ROOT.mkdir(parents=True, exist_ok=True)
#######################################################################################


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(9+!579*5y$ks*wp5p!yni&g7zv!6grhdpq#j5rq86#eiijms1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "example",
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
